### ISSUE TITLE
corenlpd - usage

### ISSUE THREAD

**Issue by RodriguezGoldstein** [lucian303/corenlpd#1]
Thanks for making the docker corenlpd build, the installation process is super easy and I didnt have any problem installing it on aws. I am wondering if you could post a short step-by-step guide on how to use the corenlpd build. Thanks!

**Comment by lucian303** [comment]
The server is an HTTP REST server and has two endpoints. Probably only the first is useful to most people and that is `GET /parse?text=This+is+a+sentence.` Pass it some text and it will analyze it with the Stanford CoreNLP and return XML output directly from CoreNLP. This will include parts of speech and relationships between different words in each sentence. That pretty much all there is to it. The second endpoint allows parsing and passing in parts of speech to use for each word. The format is word/POS word/POS. This allows you to specify a specific part of speech for any word or words and have Core NLP work with that to supply updated tags for the rest of the words in the text.

**Comment by RodriguezGoldstein** [comment]
Thanks for making this and clarifying!
